
services:
  mongo:
    image: mongo
    container_name: mongo_c
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_c
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    
    environment:
      - MONGO_URI=mongodb://mongo:27017/videmy
      - NODE_ENV=development
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_c
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
  
volumes:
  mongo_data: 